/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;
import Virginity.SystemOfEquations12;
import Virginity.SystemOfEquations13;
import Virginity.Virginity2;
import Virginity.Virginity3;
import com.mycompany.mycalculator.MyCalculator;
/**
 *
 * @author TrMTu
 */
public class MENU extends javax.swing.JFrame {
    private MyCalculator myc;
    private Virginity2 vir2;
    private Virginity3 vir3;
    private SystemOfEquations12 soe12;
    private SystemOfEquations13 soe13;
    /**
     * Creates new form MENU
     */
    public MENU() {
        vir2 = new Virginity2(this);
        vir3 = new Virginity3(this);
        soe12 = new SystemOfEquations12(this);
        soe13 = new SystemOfEquations13(this);
        initComponents();
    }
    public MENU(MyCalculator myc) {
        myc=myc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        btnptb2 = new javax.swing.JButton();
        btnHPT1_2 = new javax.swing.JButton();
        btnHPT1_3 = new javax.swing.JButton();
        btnptb3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReturn.setText("⬅");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnptb2.setText("PTB2");
        btnptb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnptb2ActionPerformed(evt);
            }
        });

        btnHPT1_2.setText("HệPTB1-2Ẩn");
        btnHPT1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHPT1_2ActionPerformed(evt);
            }
        });

        btnHPT1_3.setText("HệPTB1-3Ẩn");
        btnHPT1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHPT1_3ActionPerformed(evt);
            }
        });

        btnptb3.setText("PTB3");
        btnptb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnptb3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReturn)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHPT1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHPT1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnptb2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnptb3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReturn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnptb2)
                    .addComponent(btnptb3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHPT1_2)
                    .addComponent(btnHPT1_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        MyCalculator myc = new MyCalculator();
        this.setVisible(false);
        myc.setVisible(true);
        myc.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnptb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnptb2ActionPerformed
        // TODO add your handling code here:
        Virginity2 vir2 = new Virginity2();
        this.setVisible(false);
        vir2.setVisible(true);
        vir2.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnptb2ActionPerformed

    private void btnHPT1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHPT1_2ActionPerformed
        // TODO add your handling code here:
        SystemOfEquations12 soe1 = new SystemOfEquations12();
        soe1.setVisible(true);
        this.setVisible(false);
        soe1.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHPT1_2ActionPerformed

    private void btnHPT1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHPT1_3ActionPerformed
        // TODO add your handling code here:
        SystemOfEquations13 soe2 = new SystemOfEquations13();
        soe2.setVisible(true);
        this.setVisible(false);
        soe2.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHPT1_3ActionPerformed

    private void btnptb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnptb3ActionPerformed
        // TODO add your handling code here:
        Virginity3 vir3 = new Virginity3();
        this.setVisible(false);
        vir3.setVisible(true);
        vir3.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnptb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHPT1_2;
    private javax.swing.JButton btnHPT1_3;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnptb2;
    private javax.swing.JButton btnptb3;
    // End of variables declaration//GEN-END:variables
}
